### ISSUE TITLE
Add info about Mac OS support

### ISSUE THREAD

**Issue by vbauer** [33d/gbsim#3]
I just wanted to notify that gbsim works fine on OS X
Maybe it will be useful to add this information in the documentation?

I've just build it and run without any changes in code:
```bash
brew install sdl2
brew install libelf
cmake .
make
```

Thank you very much!

**Comment by 33d** [comment]
Thanks for the information.  It's good to hear that it just works!

**Comment by vbauer** [comment]
Thank you for the great project!

**Comment by hirotakakatoh** [comment]
Mac OS High Sierra gets an error.

---

/gamebuino/gbsim-master/gbsim/sdl_display.c:18:10: fatal error: 
'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.

---

The installed command is
brew install pkg-config
brew install sdl2
brew install libelf
cmake .
make <- error

**Comment by hirotakakatoh** [comment]
Mac OS High Sierra gets an error.

---

/gamebuino/gbsim-master/gbsim/sdl_display.c:18:10: fatal error: 
'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.

---

The installed command is
brew install pkg-config
brew install sdl2
brew install libelf
cmake .
make <- error
